name: fintrac
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.2
  http: ^1.2.2
  intl: ^0.19.0
  pie_chart: ^5.4.0
  fl_chart: ^0.68.0
  cupertino_icons: ^1.0.8
  syncfusion_flutter_charts: ^27.1.57
  image_picker: ^1.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1
  

flutter:
  uses-material-design: true

  assets:
    - lib/assets/home_icons/app_icon.png
    - lib/assets/home_icons/icon3.png
    - lib/assets/home_icons/person.png

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "lib/assets/home_icons/icon3.png"
